# Project name and minimum BuildStream version
name: spykeeos-build-meta
min-version: 2.7

# Element path where .bst files are stored
element-path: elements

aliases:
  (@): include/_private/aliases.yml

(@):
  - freedesktop-sdk.bst:include/runtime.yml

# Define plugin origins
plugins:
- origin: junction
  junction: plugins/buildstream-plugins-community.bst
  elements:
  - cargo
  sources:
  - cargo2
  - git_repo
- origin: pip
  package-name: buildstream-plugins
  elements:
  - autotools
  - meson
  sources:
  - git
  - patch

junctions:
  internal:
  - plugins/buildstream-plugins-community.bst

options:
  target_arch:
    type: arch
    variable: target-arch
    description: Target architecture
    values:
    - i686
    - x86_64

# Build environment configuration
environment:
  MAXJOBS: "%{max-jobs}"
  TMPDIR: "/tmp"

sources:
  git_repo:
    config:
      ref-format: git-describe 
  git:
    config:
      ref-format: git-describe
  cargo2:
    config:
      url: "crates:crates/"
